export const data = {
  risk: "Very High",
  casesToDate: 5000,
  activeCases: 3000,
  deaths: 200,
  recovered: 1700,
  casesPerDay: [
    // known data
    { x: -14, y: 105, toolTipContent: "14 days ago: {y}" },
    { x: -13, y: 110, toolTipContent: "13 days ago: {y}"  },
    { x: -12, y: 120, toolTipContent: "12 days ago: {y}"  },
    { x: -11, y: 140, toolTipContent: "11 days ago: {y}"  },
    { x: -10, y: 160, toolTipContent: "10 days ago: {y}"  },
    { x: -9, y: 190, toolTipContent: "9 days ago: {y}"  },
    { x: -8, y: 240, toolTipContent: "8 days ago: {y}"  },
    { x: -7, y: 290, toolTipContent: "7 days ago: {y}"  },
    { x: -6, y: 350, toolTipContent: "6 days ago: {y}"  },
    { x: -5, y: 410, toolTipContent: "5 days ago: {y}"  },
    { x: -4, y: 460, toolTipContent: "4 days ago: {y}"  },
    { x: -3, y: 510, toolTipContent: "3 days ago: {y}"  },
    { x: -2, y: 550, toolTipContent: "2 days ago: {y}"  },
    { x: -1, y: 600, toolTipContent: "1 day ago: {y}"  },
    // projections
    { x: 0, y: 640, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 0.5, y: null },
    { x: 1, y: 680, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 1.5, y: null },
    { x: 2, y: 710, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 2.5, y: null },
    { x: 3, y: 730, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 3.5, y: null },
    { x: 4, y: 750, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 4.5, y: null },
    { x: 5, y: 770, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 5.5, y: null },
    { x: 6, y: 790, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 6.5, y: null },
    { x: 7, y: 810, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 7.5, y: null },
    { x: 8, y: 825, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 8.5, y: null },
    { x: 9, y: 840, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 9.5, y: null },
    { x: 10, y: 855, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 10.5, y: null },
    { x: 11, y: 870, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 11.5, y: null },
    { x: 12, y: 880, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 12.5, y: null },
    { x: 13, y: 890, toolTipContent: "Forecast, {x} days from today: {y}" },
    { x: 13.5, y: null },
    { x: 14, y: 900, toolTipContent: "Forecast for {x} days later: {y}" }
  ]
};
